version: '3.8'

services:
  db:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    container_name: tech-house
    environment:
      MYSQL_DATABASE: "tech-house"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"